# -*- coding: utf-8 -*-
"""ResearchMethod_M4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rcsScgWlzU1RD25dZexr1Q3MZwB3ap8_
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

import io
df = pd.read_csv(io.BytesIO(uploaded['rainfall_data.csv']))

"""# Scatter Plot"""

import matplotlib.pyplot as plt
import numpy as np
from pylab import *

df.columns

subplot(1,3,1)

plt.scatter(df.YEAR,df.JAN,c='b',s=0.1,label='Jan')
plt.scatter(df.YEAR,df.FEB,c='R',s=0.1,label='Feb')
plt.legend()

subplot(1,3,2)
plt.title('India Rainfall from 1901-2017 based on months', fontsize=20)
plt.scatter(df.YEAR,df.JUN,c='b',s=0.1,label='Jun')
plt.scatter(df.YEAR,df.JUL,c='R',s=0.1,label='Jul')
plt.legend()

subplot(1,3,3)

plt.scatter(df.YEAR,df.OCT,c='b',s=0.1,label='Oct')
plt.scatter(df.YEAR,df.NOV,c='R',s=0.1,label='Nov')
plt.legend()

plt.title('India Rainfall from 1901-2017 based on months', fontsize=20)
plt.scatter(df.YEAR,df.JUN,c='b',s=0.3,label='Jun')
plt.scatter(df.YEAR,df.JUL,c='R',s=0.3,label='Jul')
plt.scatter(df.YEAR,df.AUG,c='y',s=0.3,label='Aug')
plt.legend()

plt.title('India Rainfall from 1901-2017 based on months', fontsize=20)
plt.scatter(df.YEAR,df.OCT,c='b',s=0.3,label='Oct')
plt.scatter(df.YEAR,df.NOV,c='R',s=0.3,label='Nov')
plt.scatter(df.YEAR,df.DEC,c='y',s=0.3,label='Dec')
plt.legend()

plt.title('Annual Rainfall from 1901-2017', fontsize=20)
plt.scatter(df.YEAR,df.ANNUAL,c='r',s=1,label='Annual')
plt.legend()

"""# Box Plot"""

df3=df[df['YEAR']>2010]
df3.boxplot(by ='YEAR', column =['ANNUAL'], grid = False)

"""# Line Plot"""

df1=df[df['SUBDIVISION']=='Lakshadweep']
df1=df1[[ 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL',
       'AUG', 'SEP', 'OCT', 'NOV', 'DEC', 'ANNUAL']]

df1 = df1.cumsum();
df1.plot(style='.-')

df2=df[[ 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL',
       'AUG', 'SEP', 'OCT', 'NOV', 'DEC', 'ANNUAL']]
df2 = df2.cumsum();
df2.plot(style='.-')

